name: tadween_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  uuid: ^3.0.6
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^8.0.3
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.6
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  fl_chart: ^0.70.2
  meta: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true